### ISSUE TITLE
Not clear what "this file" refers to

### ISSUE THREAD

**Issue by muyncky** [vuestorefront/prestashop#130]
### Provide a description of requested docs changes

It is not clear what "this file" is referring to on line `docs/guide/getting-started.md:20`.

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
`packages/theme/middleware.config.js` missed,

thanks for noticing. Added to `develop` branch.
