### ISSUE TITLE
[Bug]: PrestaShop set two cookies and caused problems with session management

### ISSUE THREAD

**Issue by samberrry** [vuestorefront/prestashop#137]
### Actual Behavior

When PrestaShop website tries to set two cookies we will encounter issues. However, according to the documentation we must have only one cookie:
https://devdocs.prestashop-project.org/8/development/components/cookie/#limits
```
PrestaShop will create only one cookie, in the $_COOKIE array, with each key and value data appended to a string and finally encrypted for safety reasons.

```
![Screen Shot 2023-08-12 at 12 05 29 PM](https://github.com/vuestorefront-community/prestashop/assets/20775532/3ef0f559-1f91-420c-871c-641be08f0a5a)

### How I encountered the issue? 
When I logged into the shop and tried to do an add to cart/ or checking account info, the user will be logged out on front-end. Why? because it uses wrong cookie.

**Comment by samberrry** [comment]
I think we should not handle this situation on front-end.

**Comment by samberrry** [comment]
third-party modules can cause having many cookies: 
https://github.com/PrestaShop/PrestaShop/issues/29868

**Comment by samberrry** [comment]
This issue is not related to front, it must be fixed on back-end instance, so I close it.

**Comment by SoulRaven** [comment]
+1 same problem here PS 8.2.1, PHP8.1, nginx.
frequent session timeout, redirect to login page.

**Comment by samberrry** [comment]
@SoulRaven we no longer support this repo, isntead you can take a look at: https://github.com/binshops/react-ecommerce
